import vine from '@vinejs/vine';

const settingSchema = vine.object({
  active: vine.boolean(),
  defaultLanguage: vine.enum(['th', 'en', 'jp']),
  textDisplay: vine.string().optional(),
  theme: vine.enum(['light', 'dark']).optional(),
  openDays: vine.array(
    vine.object({
      day: vine.array(
        vine.enum([
          'Sunday',
          'Monday',
          'Tuesday',
          'Wednesday',
          'Thursday',
          'Friday',
          'Saturday',
        ]),
      ),
      openTime: vine.string().regex(/^\d{2}:\d{2}$/),
      closeTime: vine.string().regex(/^\d{2}:\d{2}$/),
    }),
  ),
});

const addressSchema = vine.object({
  active: vine.boolean(),
  language: vine.string(),
  isMain: vine.boolean(),
  name: vine.string(),
  city: vine.string(),
  province: vine.string(),
  postalCode: vine.string().maxLength(5),
  roomNo: vine.string().optional(),
  floorNo: vine.string().optional(),
  village: vine.string().optional(),
  villageNo: vine.string().optional(),
  houseNo: vine.string().optional(),
  alley: vine.string().optional(),
  road: vine.string().optional(),
  building: vine.string().optional(),
  nation: vine.string().optional(),
  district: vine.string().optional(),
  subDistrict: vine.string().optional(),
  note: vine.string().optional(),
});

const profileSchema = vine.object({
  firstName: vine.string(),
  lastName: vine.string().optional(),
  birthDate: vine.string().optional(),
  phone: vine.string().maxLength(15).optional(),
});

const userSchema = vine.object({
  active: vine.boolean(),
  status: vine.string(),
  email: vine.string().email(),
  password: vine.string(),
  userName: vine.string().optional(),
  profile: profileSchema.clone(),
});

export const schemaCreateBranch = vine.object({
  active: vine.boolean(),
  organizationId: vine.string().uuid(),
  isCreateUser: vine.boolean(),
  fromType: vine.enum(['ordinary_person', 'juristic_person']),
  status: vine.enum([
    'newly_registered',
    'active',
    'loyal_customer',
    'at_risk',
    'churned',
  ]),
  type: vine.enum([
    'human',
    'ordinary_partnership',
    'shop',
    'bop',
    'company_limited',
    'public_company_limited',
    'limited_partnership',
    'foundation',
    'association',
    'joint_venture',
    'others',
  ]),
  logoUrl: vine.string().optional(),
  nameTh: vine.string(),
  nameEn: vine.string(),
  taxId: vine.string(),
  descriptionsTh: vine.string().optional(),
  descriptionsEn: vine.string().optional(),
  openingDate: vine.string().optional(),
  registerVat: vine.boolean(),
  websiteUrl: vine.string().optional(),
  domainName: vine.string(),
  contactName: vine.string(),
  contactPhone: vine.string().maxLength(15),
  contactEmail: vine.string().email(),
  contactWebsite: vine.string().optional(),
  contactFacebook: vine.string().optional(),
  contactLine: vine.string().optional(),
  contactWhatsapp: vine.string().optional(),
  contactNote: vine.string().optional(),
  address: addressSchema.clone(),
  user: userSchema.clone(),
  setting: settingSchema.clone(),
});

export const schemaUpdateBranch = vine.object({
  organizationId: vine.string().uuid(),
  nameTh: vine.string(),
  nameEn: vine.string(),
  taxId: vine.string(),
  active: vine.boolean(),
  status: vine.enum([
    'newly_registered',
    'active',
    'loyal_customer',
    'at_risk',
    'churned',
  ]),
  fromType: vine.enum(['ordinary_person', 'juristic_person']),
  type: vine.enum([
    'human',
    'ordinary_partnership',
    'shop',
    'bop',
    'company_limited',
    'public_company_limited',
    'limited_partnership',
    'foundation',
    'association',
    'joint_venture',
    'others',
  ]),
  descriptionsTh: vine.string().optional(),
  descriptionsEn: vine.string().optional(),
  registerVat: vine.boolean(),
  openingDate: vine.string().optional(),
  websiteUrl: vine.string().optional(),
  domainName: vine.string(),
  contactName: vine.string(),
  contactEmail: vine.string().email(),
  contactPhone: vine.string().maxLength(15),
  contactWebsite: vine.string().optional(),
  businessEmail: vine.string().email().optional(),
  contactFacebook: vine.string().optional(),
  contactLine: vine.string().optional(),
  contactWhatsapp: vine.string().optional(),
  contactNote: vine.string().optional(),
  // addresses: addressesSchema.clone(),
  // setting: settingSchema.clone(),
});
