export const renderForm = [
  {
    name: 'prefix',
    label: 'คำนำหน้า',
    placeholder: 'เลือกคำนำหน้า',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'Mr.', label: 'นาย' },
      { value: 'Mrs.', label: 'นาง' },
      { value: 'Miss', label: 'นางสาว' },
    ],
    require: true,
  },
  {
    name: 'firstName',
    label: 'ชื่อ',
    placeholder: 'ชื่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    require: true,
  },
  {
    name: 'lastName',
    label: 'นามสกุล',
    placeholder: 'นามสกุล',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    require: true,
  },
  {
    name: 'birthDate',
    label: 'วัน/เดือน/ปีเกิด',
    placeholder: 'เลือก',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'DatePickerFormField',
  },
  {
    name: 'discordGuid',
    label: 'Discord GUID',
    placeholder: 'Discord GUID',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    require: true,
  },
  {
    name: 'phone',
    label: 'เบอร์โทรศัพท์',
    placeholder: 'เบอร์โทรศัพท์',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    require: true,
  },
];
