export const renderForm = [
  {
    label: 'ข้อมูลผู้ใช้',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'SectionLabelForm',
  },
  {
    name: 'email',
    label: 'อีเมล',
    placeholder: 'อีเมล',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    require: true,
  },
  {
    name: 'userName',
    label: 'ชื่อผู้ใช้',
    placeholder: 'ชื่อผู้ใช้',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    require: true,
  },
  {
    name: 'password',
    label: 'รหัสผ่าน',
    placeholder: 'รหัสผ่าน',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    require: true,
  },
  {
    name: 'active',
    label: 'เปิดใช้งาน',
    col: { xs: 12, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SwitchFormField',
    require: true,
  },
  {
    name: 'roleId',
    label: 'ตำแหน่ง',
    placeholder: 'เลือกตำแหน่ง',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: '4', label: 'manager' },
      { value: '5', label: 'supervisor' },
      { value: '6', label: 'employee' },
    ],
    require: true,
  },

  {
    name: 'profix',
    label: 'คำนำหน้า',
    placeholder: 'เลือกคำนำหน้า',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'Mr.', label: 'นาย' },
      { value: 'Mrs.', label: 'นาง' },
      { value: 'Miss', label: 'นางสาว' },
    ],
    require: true,
  },
  {
    name: 'firstName',
    label: 'ชื่อ',
    placeholder: 'ชื่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    require: true,
  },
  {
    name: 'lastName',
    label: 'นามสกุล',
    placeholder: 'นามสกุล',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    require: true,
  },
  {
    name: 'birthDate',
    label: 'วัน/เดือน/ปีเกิด',
    placeholder: 'เลือก',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'DatePickerFormField',
  },

  {
    name: 'phone',
    label: 'เบอร์โทรศัพท์',
    placeholder: 'เบอร์โทรศัพท์',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    require: true,
  },
];
