import { TagFilled } from "@ant-design/icons";

export const renderForm = [
  {
    label: 'ข้อมูลสาขา',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'LabelForm',
  },
  {
    name: 'taxId',
    label: 'เลขไอดี',
    placeholder: 'กรอกเลขไอดี',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'nameTh',
    label: 'ชื่อสาขา',
    placeholder: 'กรอกชื่อสาขา',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'logoUrl',
    label: 'ลิ้งค์โลโก้',
    placeholder: 'กรอกลิ้งค์โลโก้',
    require: true,
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'type',
    label: 'ประเภทสาขา',
    placeholder: 'กรอกประเภทสาขา',
    require: true,
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'fromType',
    label: 'รูปแบบสาขา',
    placeholder: 'กรอกรูปแบบสาขา',
    require: true,
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'contactEmail',
    label: 'อีเมลล์',
    placeholder: 'กรอกอีเมลล์',
    col: { xs: 24, sm: 12, md: 12, lg: 6, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'websiteUrl',
    label: 'ลิ้งค์เว็ปไซต์',
    placeholder: 'กรอกลิ้งค์เว็ปไซต์',
    col: { xs: 24, sm: 12, md: 12, lg: 6, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'contactPhone',
    label: 'เบอร์โทรติดต่อ',
    placeholder: 'กรอกเบอร์โทร',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    icon: <TagFilled />,
    label: 'ข้อมูลตามทะเบียน',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 24 },
    type: 'LabelForm',
  },
  {
    name: ['address', 'active'],
    label: 'ทำงานอยู่',
    placeholder: 'ทำงานอยู่',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'SwitchFormField',
  },
  {
    name: ['address', 'descriptionsTh'],
    label: 'คำอธิบาย',
    placeholder: 'กรอกคำอธิบาย',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['address', 'addressType'],
    label: 'ประเภทที่อยู่',
    placeholder: 'กรอกประเภทที่อยู่',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['address', 'province'],
    label: 'จังหวัด',
    placeholder: 'กรอกจังหวัด',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['address', 'district'],
    label: 'เขต',
    placeholder: 'กรอกเขต',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['address', 'subDistrict'],
    label: 'ตำบล',
    placeholder: 'กรอกตำบล',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['address', 'address'],
    label: 'ที่อยู่',
    placeholder: 'กรอกที่อยู่',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['address', 'postalCode'],
    label: 'รหัสไปรษณีย์',
    placeholder: 'รหัสไปรษณีย์',
    col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
];

export const renderEditForm = [
    {
        label: 'แก้ไขข้อมูลสาขา',
        col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
        type: 'LabelForm',
      },
      {
        name: 'taxId',
        label: 'เลขไอดี',
        placeholder: 'กรอกเลขไอดี',
        col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
        type: 'TextboxFormField',
      },
      {
        name: 'nameTh',
        label: 'ชื่อสาขา',
        placeholder: 'กรอกชื่อสาขา',
        col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
        type: 'TextboxFormField',
      },
      {
        name: 'logoUrl',
        label: 'ลิ้งค์โลโก้',
        placeholder: 'กรอกลิ้งค์โลโก้',
        require: true,
        col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
        type: 'TextboxFormField',
      },
      {
        name: 'businessType',
        label: 'ประเภทสาขา',
        placeholder: 'กรอกประเภทสาขา',
        require: true,
        col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
        type: 'TextboxFormField',
      },
      {
        name: 'businessModel',
        label: 'รูปแบบสาขา',
        placeholder: 'กรอกรูปแบบสาขา',
        require: true,
        col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
        type: 'TextboxFormField',
      },
      {
        name: 'contactEmail',
        label: 'อีเมลล์',
        placeholder: 'กรอกอีเมลล์',
        col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
        type: 'TextboxFormField',
      },
      {
        name: 'websiteUrl',
        label: 'ลิ้งค์เว็ปไซต์',
        placeholder: 'กรอกลิ้งค์เว็ปไซต์',
        col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
        type: 'TextboxFormField',
      },
      {
        name: 'contactPhone',
        label: 'เบอร์โทรติดต่อ',
        placeholder: 'กรอกเบอร์โทร',
        col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
        type: 'TextboxFormField',
      },
      {
        name: 'active',
        label: 'พร้อมใช้งาน',
        placeholder: 'พร้อมใช้งาน',
        col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
        type: 'CheckboxFormField',
      },
      {
        icon: <TagFilled />,
        label: 'ข้อมูลที่อยู่',
        col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
        type: 'LabelForm',
      },
      {
        name: 'descriptionsTh',
        label: 'คำอธิบาย',
        placeholder: 'กรอกคำอธิบาย',
        col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
        type: 'TextboxFormField',
      },
      {
        name: 'addressType',
        label: 'ประเภทที่อยู่',
        placeholder: 'กรอกประเภทที่อยู่',
        col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
        type: 'TextboxFormField',
      },
      {
        name: 'province',
        label: 'จังหวัด',
        placeholder: 'กรอกจังหวัด',
        col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
        type: 'TextboxFormField',
      },
      {
        name: 'district',
        label: 'เขต',
        placeholder: 'กรอกเขต',
        col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
        type: 'TextboxFormField',
      },
      {
        name: 'subdistrict',
        label: 'ตำบล',
        placeholder: 'กรอกตำบล',
        col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
        type: 'TextboxFormField',
      },
      {
        name: 'address',
        label: 'ที่อยู่',
        placeholder: 'กรอกที่อยู่',
        col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
        type: 'TextboxFormField',
      },
      {
        name: 'postalCode',
        label: 'รหัสไปรษณีย์',
        placeholder: 'รหัสไปรษณีย์',
        col: { xs: 24, sm: 12, md: 12, lg: 12, xl: 12 },
        type: 'TextboxFormField',
      },
]