import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '@/styles/globals.css';
import React from 'react';
import { NextUIProvider } from '@nextui-org/react';
import { Toaster } from 'sonner';

const ibmPlexSans = localFont({
  src: '../assets/fonts/IBMPlexSansThai-Regular.ttf',
  variable: '--font-ibm-sans',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ibmPlexSans.variable}  antialiased`}>
        <NextUIProvider>
          <Toaster position="bottom-left" richColors expand />
          <main>{children}</main>
        </NextUIProvider>
      </body>
    </html>
  );
}
