import { TagFilled } from "@ant-design/icons";

export const renderForm = [
    {
      name: "active",
      label: "เปิดใช้งาน",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 4 },
      type: "SwitchFormField",
    },
    {
      name: "businessType",
      label: "รูปแบบธุรกิจ",
      placeholder: "รูปแบบธุรกิจ",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
      type: "SelectFormField",
      option: [
        { value: "Single", label: "เดี่ยว" },
        { value: "Duo", label: "คู่" },
        { value: "Team", label: "ทีม" },
      ],
    },
    {
      name: "taxId",
      label: "เลขทะเบียน 13 หลัก",
      placeholder: "เลขทะเบียน 13 หลัก",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 8 },
      type: "TextboxFormField",
      require: true,
      message: "กรุณากรอกข้อมูลเลขทะเบียน 13 หลัก ( เช่น 0123456789101 ) ",
    },
    {
      name: "businessName",
      label: "ชื่อกิจการ",
      placeholder: "ชื่อกิจการ",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
      type: "TextboxFormField",
      require: true,
      message: "กรุณากรอกชื่อกิจการ",
    },
    {
      name: "businessDescription",
      label: "คำอธิบายธุรกิจ",
      placeholder: "คำอธิบายธุรกิจ",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
      type: "TextAreaFormField",
      require: true,
    },
    {
      name: "businessRegister",
      label: "วันที่จดทะเบียน",
      placeholder: "วันที่จดทะเบียน",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
      type: "DatePickerFormField",
    },
    {
      name: "registerVat",
      label: "จดทะเบียนภาษีมูลค่าเพิ่ม",
      placeholder: "จดทะเบียนภาษีมูลค่าเพิ่ม",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 24 },
      type: "CheckboxFormField",
      // require: true,
    },

    {
      icon: <TagFilled />,
      label: "ข้อมูลช่องทางการติดต่อ",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 24 },
      type: "LabelForm",
    },
    {
      name: "businessPhone",
      label: "เบอร์โทรศัพท์สำนักงาน",
      placeholder: "เบอร์โทรศัพท์สำนักงาน",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 8 },
      type: "TextboxFormField",
      require: true,
      message: "กรุณากรอกเบอร์โทรศัพท์สำนักงาน  ",
    },
    {
      name: "businessEmail",
      label: "อีเมลล์สำนักงาน",
      placeholder: "อีเมลล์สำนักงาน",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 8 },
      type: "TextboxFormField",
    },
    {
      name: "websiteUrl",
      label: "เว็บไซต์สำนักงาน",
      placeholder: "เว็บไซต์สำนักงาน",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 8 },
      type: "TextboxFormField",
    },
    {
      name: "contactPhone",
      label: "เบอร์โทรศัพท์ติดต่อ",
      placeholder: "เบอร์โทรศัพท์ติดต่อ",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 8 },
      type: "TextboxFormField",
      require: true,
      message: "กรุณากรอกเบอร์โทรศัพท์ติดต่อ  ",
    },
    {
      name: "contactEmail",
      label: "อีเมลล์ติดต่อ",
      placeholder: "อีเมลล์ติดต่อ",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 8 },
      type: "TextboxFormField",
      require: true,
      message: "กรุณากรอกอีเมลล์ติดต่อ  ",
    },
    {
      icon: <TagFilled />,
      label: "ข้อมูลตามทะเบียน",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 24 },
      type: "LabelForm",
    },
    {
      name: ["address", "address"],
      label: "ที่อยู่",
      placeholder: "ที่อยู่",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 8 },
      type: "TextboxFormField",
    },
    {
      name: ["address", "addressType"],
      label: "ประเภทที่อยู่",
      placeholder: "ประเภทที่อยู่",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
      type: "SelectFormField",
      option: [
        { value: "Single", label: "Home" },
        { value: "Duo", label: "Apartment" },
        { value: "Team", label: "Detached House" },
      ],
    },
    {
      name: ["address", "descriptions"],
      label: "คำอธิบายเกี่ยวกับที่อยู่",
      placeholder: "คำอธิบายเกี่ยวกับที่อยู่",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 24 },
      type: "TextAreaFormField",
    },
    {
      name: "country",
      label: "ประเทศ",
      placeholder: "ประเทศ",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 8 },
      type: "TextboxFormField",
    },
    {
      name: ["address", "subDistrict"],
      label: "แขวง/ตำบล",
      placeholder: "แขวง/ตำบล",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 8 },
      type: "TextboxFormField",
    },
    {
      name: ["address", "district"],
      label: "เขต/อำเภอ",
      placeholder: "เขต/อำเภอ",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 8 },
      type: "TextboxFormField",
    },
    {
      name: ["address", "province"],
      label: "จังหวัด",
      placeholder: "จังหวัด",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 8 },
      type: "TextboxFormField",
      require: true,
      message: "กรุณากรอกจังหวัด",
    },
    {
      name: ["address", "postalCode"],
      label: "รหัสไปรษณีย์",
      placeholder: "รหัสไปรษณีย์",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 8 },
      type: "TextboxFormField",
      require: true,
      message: "กรุณากรอกรหัสไปรษณีย์",
    },
    {
      icon: <TagFilled />,
      label: "ที่อยู่ตามเอกสาร",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
      type: "LabelForm",
    },
    {
      name: "branchType",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
      type: "RadioFormField",
      option: [
        { value: "same", label: "ใช้ข้อมูลที่อยู่ตามทะเบียน" },
        { value: "new", label: "ข้อมูลใหม่" },
      ],
    },

    {
      name: ["address", "address"],
      label: "ที่อยู่",
      placeholder: "ที่อยู่",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 8 },
      type: "TextboxFormField",
    },
    {
      name: ["address", "addressType"],
      label: "ประเภทที่อยู่",
      placeholder: "ประเภทที่อยู่",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
      type: "SelectFormField",
      option: [
        { value: "Single", label: "Home" },
        { value: "Duo", label: "Apartment" },
        { value: "Team", label: "Detached House" },
      ],
    },
    {
      name: "descriptions",
      label: "คำอธิบายเกี่ยวกับที่อยู่",
      placeholder: "คำอธิบายเกี่ยวกับที่อยู่",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 24 },
      type: "TextAreaFormField",
    },
    {
      name: ["address", "country"],
      label: "ประเทศ",
      placeholder: "ประเทศ",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 8 },
      type: "TextboxFormField",
    },
    {
      name: ["address", "subDistrict"],
      label: "แขวง/ตำบล",
      placeholder: "แขวง/ตำบล",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 8 },
      type: "TextboxFormField",
    },
    {
      name: ["address", "district"],
      label: "เขต/อำเภอ",
      placeholder: "เขต/อำเภอ",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 8 },
      type: "TextboxFormField",
    },
    {
      name: ["address", "province"],
      label: "จังหวัด",
      placeholder: "จังหวัด",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 8 },
      type: "TextboxFormField",
    },
    {
      name: ["address", "postalCode"],
      label: "รหัสไปรษณีย์",
      placeholder: "รหัสไปรษณีย์",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 8 },
      type: "TextboxFormField",
    },
    {
      name: ["address", "active"],
      label: "เปิดใช้งาน",
      col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 4 },
      type: "SwitchFormField",
    },
  ];