export const organizeData = [
    {
      key: "1",
      id: 1,
      logoUrl: "https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg",
      businessName: "Business 1",
      businessDescription: "Description for business 1",
      businessRegister: "2023-01-01",
      businessPhone: "0123456789",
      default_user: "User 1",
      timeused: "1 year",
      active: true,
    },
    {
      key: "2",
      id: 2,
      logoUrl: "https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg",
      businessName: "Business 2",
      businessDescription: "Description for business 2",
      businessRegister: "2023-02-01",
      businessPhone: "9876543210",
      default_user: "User 2",
      timeused: "2 years",
      active: false,
    },
    {
      key: "3",
      id: 3,
      logoUrl: "https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg",
      businessName: "Business 3",
      businessDescription: "Description for business 3",
      businessRegister: "2023-03-01",
      businessPhone: "1234567890",
      default_user: "User 3",
      timeused: "3 years",
      active: true,
    },
  ];
  