export type Participant = {
  id: string;
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
  createdBy: string | null;
  createdById: string | null;
  updatedBy: string | null;
  updatedById: string | null;
  deletedBy: string | null;
  deletedById: string | null;
  chatRoomId: string;
  participantType: string | null;
  participantId: string;
  externalId: string | null;
  displayName: string;
  imageUrl?: string | null;
  role: string | null;
  isMain: boolean;
  isMuted: boolean;
  lastReadAt: string | null;
  lastReadMessageId: string | null;
  meta: Record<string, unknown> | null;
  user?: ParticipantUser | null;
};

export type ParticipantUser = {
  id: string;
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
  createdBy: string | null;
  createdById: string | null;
  updatedBy: string | null;
  updatedById: string | null;
  deletedBy: string | null;
  deletedById: string | null;
  email: string;
  userName: string;
  active: boolean;
  activate: boolean;
  status: string | null;
  mainDepartment: string;
  tempPassword: string | null;
  mustChangePassword: boolean;
  isOnboarding: boolean;
  roleId: string;
  organizationGroupId: string | null;
  organizationId: string | null;
  branchId: string | null;
  meta?: Record<string, unknown> | null;
};
