export const renderCreateForm = [
  /*Organize Section*/
  //FIXME:add upload logo url

  {
    label: 'ข้อมูลองค์กร',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'SectionLabelForm',
  },
  {
    label: 'รูปภาพโลโก้องค์กร',
    col: { xs: 24, sm: 24, md: 6, lg: 6, xl: 6 },
    type: 'UploadFile',
    name: 'file1',
  },
  {
    name: ['organization', 'active'],
    label: 'ปิดองค์กร',
    col: { xs: 24, sm: 24, md: 18, lg: 18, xl: 18 },
    type: 'ActiveCard',
    title: 'ปิดองค์กร',
    description:
      'ใช้สำหรับการปิดหรือยุติการทำงานขององค์กรในระบบหรือเว็บไซต์ ซึ่งอาจรวมถึงการปิดการใช้งานบัญชีองค์กร',
    rule: [{ required: true, message: 'กรุณาเลือกเปิดปิดองค์กร!' }],
  },

  {
    name: ['organization', 'fromType'],
    label: 'ประเภทธุรกิจ',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'RadioFormField',
    options: [
      { value: 'ordinary_person', label: 'บุคคลธรรมดา' },
      { value: 'juristic_person', label: 'นิติบุคคล' },
    ],
    defaultValue: 'ordinary_person',
    rule: [{ required: true, message: 'กรุณาเลือกประเภทธุรกิจ!' }],
  },
  {
    name: ['organization', 'status'],
    label: 'สถานะธุรกิจ',
    placeholder: 'สถานะธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'newly_registered', label: 'ลูกค้าที่เพิ่งลงทะเบียนใหม่ในระบบ' },
      { value: 'active', label: 'ลูกค้าที่ใช้งานอย่างต่อเนื่อง' },
      { value: 'loyal_customer', label: 'ลูกค้าที่มีความภักดีต่อระบบ' },
      { value: 'at_risk', label: 'ลูกค้าที่อาจจะเสี่ยงต่อการหยุดใช้งาน' },
      { value: 'churned', label: 'ลูกค้าที่ได้หยุดใช้บริการหรือยกเลิกบัญชี' },
    ],
    defaultValue: 'newly_registered',
    rule: [{ required: true, message: 'กรุณาเลือกสถานะธุรกิจ!' }],
  },
  {
    name: ['organization', 'type'],
    label: 'รูปแบบธุรกิจ',
    placeholder: 'รูปแบบธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'company_limited', label: 'บริษัทจำกัด' },
      { value: 'public_company_limited', label: 'บริษัทมหาชนจำกัด' },
      { value: 'limited_partnership', label: 'ห้างหุ้นส่วนจำกัด' },
      { value: 'foundation', label: 'มูลนิธิ' },
      { value: 'association', label: 'สมาคม' },
      { value: 'joint_venture', label: 'กิจการร่วมค้า' },
      { value: 'others', label: 'อื่นๆ' },
    ],
    rule: [{ required: true, message: 'กรุณาเลือกรูปแบบธุรกิจ!' }],
  },
  {
    name: ['organization', 'nameTh'],
    label: 'ชื่อกิจการ (ภาษาไทย)',
    placeholder: 'ชื่อกิจการ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกชื่อกิจการ (ภาษาไทย)!' }],
    isName: true,
    errorUniqMessage: 'ไม่สามารถใช้งานชื่อนี้ได้',
  },
  {
    name: ['organization', 'nameEn'],
    label: 'ชื่อกิจการ (English)',
    placeholder: 'ชื่อกิจการ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกชื่อกิจการ (English)!' }],
    isName: true,
    errorUniqMessage: 'ไม่สามารถใช้งานชื่อนี้ได้',
  },
  {
    name: ['organization', 'taxId'],
    label: 'เลขทะเบียน 13 หลัก',
    placeholder: 'เลขทะเบียน 13 หลัก',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'LengthInput',
    maxLength: 13,
    rule: [{ required: true, message: 'กรุณากรอกเลขทะเบียน 13 หลัก!' }],
    errorUniqMessage: 'ไม่สามารถใช้งานเลขทะเบียน13หลักนี้ได้',
  },

  {
    name: ['organization', 'descriptionsTh'],
    label: 'คำอธิบายธุรกิจ (ภาษาไทย)',
    placeholder: 'คำอธิบายธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextAreaFormField',
  },
  {
    name: ['organization', 'descriptionsEn'],
    label: 'คำอธิบายธุรกิจ (English)',
    placeholder: 'คำอธิบายธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextAreaFormField',
  },

  {
    name: ['organization', 'openingDate'],
    label: 'วันที่จดทะเบียน',
    placeholder: 'วันที่จดทะเบียน',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'DatePickerFormField',
  },
  {
    name: ['organization', 'registerVat'],
    label: 'จดทะเบียนภาษีมูลค่าเพิ่ม',
    placeholder: 'จดทะเบียนภาษีมูลค่าเพิ่ม',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SwitchFormField',
    rule: [
      {
        required: true,
        message: 'กรุณาเลือกว่าจดทะเบียนภาษีมูลค่าเพิ่มหรือไม่!',
      },
    ],
    checkedText: 'จด',
    unCheckedText: 'ไม่ได้จด',
  },
  {
    name: ['organization', 'websiteUrl'],
    label: 'เว็ปไซต์สำนักงาน',
    placeholder: 'เว็ปไซต์สำนักงาน',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['organization', 'domainName'],
    label: 'ชื่อโดเมน',
    placeholder: 'ชื่อโดเมน ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [
      { required: true, message: 'กรุณากรอกชื่อโดเมน!' },
      {
        pattern: /^(?!-)([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}(?<!-)$/,
        message:
          'กรุณากรอกชื่อโดเมนให้ถูกต้อง เช่น utotech.com หรือ utotech.co.th',
      },
    ],
  },
  {
    label: 'ข้อมูลช่องทางการติดต่อขององค์กร',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'SectionLabelForm',
  },
  {
    name: ['organization', 'contactName'],
    label: 'รายชื่อผู้ติดต่อ',
    placeholder: 'รายชื่อผู้ติดต่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกรายชื่อผู้ติดต่อ!' }],
  },
  {
    name: ['organization', 'contactPhone'],
    label: 'เบอร์โทรศัพท์ติดต่อ',
    placeholder: 'เบอร์โทรศัพท์ติดต่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'PhoneInput',
    rule: [{ required: true, message: 'กรุณากรอกเบอร์โทรศัพท์ติดต่อ!' }],
  },
  {
    name: ['organization', 'contactEmail'],
    label: 'อีเมลติดต่อ',
    placeholder: 'อีเมลติดต่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกเบอร์อีเมลติดต่อ!' }],
  },

  {
    name: ['organization', 'contactWebsite'],
    label: 'เว็บไซต์ติดต่อ',
    placeholder: 'เว็บไซต์ติดต่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['organization', 'contactFacebook'],
    label: 'Facebook',
    placeholder: 'Facebook',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['organization', 'contactLine'],
    label: 'Line ID',
    placeholder: 'line Id',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },

  {
    name: ['organization', 'contactWhatsapp'],
    label: 'WhatsApp',
    placeholder: 'WhatsApp',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['organization', 'contactNote'],
    label: 'ข้อมูลการติดต่อ',
    placeholder: 'ข้อมูลการติดต่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },

  {
    label: 'ข้อมูลที่อยู่องค์กร',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'SectionLabelForm',
  },
  {
    name: ['organization', 'address', 'name'],
    label: 'ชื่อที่อยู่',
    placeholder: 'ชื่อที่อยู่',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกชื่อที่อยู่!' }],
  },
  {
    name: ['organization', 'address', 'city'],
    label: 'เมือง',
    placeholder: 'เมือง',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกชื่อเมือง!' }],
  },
  {
    name: ['organization', 'address', 'province'],
    label: 'จังหวัด',
    placeholder: 'จังหวัด',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกชื่อจังหวัด!' }],
  },
  {
    name: ['organization', 'address', 'postalCode'],
    label: 'รหัสไปรษณีย์',
    placeholder: 'รหัสไปรษณีย์',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกรหัสไปรษณีย์!' }],
  },
  {
    name: ['organization', 'address', 'roomNo'],
    label: 'เลขห้อง',
    placeholder: 'เลขห้อง',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: ['organization', 'address', 'floorNo'],
    label: 'ชั้นที่อยู่',
    placeholder: 'ชั้นที่อยู่',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: ['organization', 'address', 'village'],
    label: 'หมู่บ้าน',
    placeholder: 'หมู่บ้าน',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: ['organization', 'address', 'villageNo'],
    label: 'เลขหมู่บ้าน',
    placeholder: 'เลขหมู่บ้าน',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: ['organization', 'address', 'houseNo'],
    label: 'บ้านเลขที่',
    placeholder: 'บ้านเลขที่',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: ['organization', 'address', 'alley'],
    label: 'ตรอก',
    placeholder: 'ตรอก',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: ['organization', 'address', 'road'],
    label: 'ถนน',
    placeholder: 'ถนน',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: ['organization', 'address', 'building'],
    label: 'อาคาร',
    placeholder: 'อาคาร',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },

  {
    name: ['organization', 'address', 'nation'],
    label: 'ประเทศ',
    placeholder: 'ประเทศ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },

  {
    name: ['organization', 'address', 'district'],
    label: 'เขต/อำเภอ',
    placeholder: 'เขต/อำเภอ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['organization', 'address', 'subDistrict'],
    label: 'แขวง/ตำบล',
    placeholder: 'แขวง/ตำบล',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },

  {
    name: ['organization', 'address', 'note'],
    label: 'หมายเหตุ',
    placeholder: 'หมายเหตุ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextAreaFormField',
  },
];

export const renderCreateBranchForm = [
  /*Branch Section*/

  //FIXME:add upload logo url
  {
    label: 'ข้อมูลสาขา',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'SectionLabelForm',
  },
  {
    label: 'รูปภาพโลโก้สาขา',
    col: { xs: 24, sm: 24, md: 6, lg: 6, xl: 6 },
    type: 'UploadFile',
    name: 'file2',
  },
  {
    name: ['branch', 'active'],
    label: 'ปิดสาขา',
    col: { xs: 24, sm: 24, md: 18, lg: 18, xl: 18 },
    type: 'ActiveCard',
    title: 'ปิดสาขา',
    description:
      'ใช้สำหรับการปิดหรือยุติการทำงานของสาขาในระบบหรือเว็บไซต์ ซึ่งอาจรวมถึงการปิดการใช้งานบัญชีสาขา',
    rule: [{ required: true, message: 'กรุณาเลือกเปิดปิดสาขา!' }],
  },
  {
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'ButtonGetOrganizeValue',
  },
  {
    name: ['branch', 'isMain'],
    label: 'ประเภทสาขา',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'RadioFormField',
    options: [
      { value: true, label: 'สำนักงานใหญ่' },
      { value: false, label: 'สาขา' },
    ],
    defaultValue: true,
    rule: [{ required: true, message: 'กรุณาเลือกประเภทสาขา!' }],
  },
  {
    name: ['branch', 'fromType'],
    label: 'ประเภทธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'RadioFormField',
    options: [
      { value: 'ordinary_person', label: 'บุคคลธรรมดา' },
      { value: 'juristic_person', label: 'นิติบุคคล' },
    ],
    defaultValue: 'ordinary_person',
    rule: [{ required: true, message: 'กรุณาเลือกประเภทธุรกิจ!' }],
  },
  {
    name: ['branch', 'type'],
    label: 'รูปแบบธุรกิจ',
    placeholder: 'รูปแบบธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'company_limited', label: 'บริษัทจำกัด' },
      { value: 'public_company_limited', label: 'บริษัทมหาชนจำกัด' },
      { value: 'limited_partnership', label: 'ห้างหุ้นส่วนจำกัด' },
      { value: 'foundation', label: 'มูลนิธิ' },
      { value: 'association', label: 'สมาคม' },
      { value: 'joint_venture', label: 'กิจการร่วมค้า' },
      { value: 'others', label: 'อื่นๆ' },
    ],
    rule: [{ required: true, message: 'กรุณาเลือกรูปแบบธุรกิจ!' }],
  },
  {
    name: ['branch', 'status'],
    label: 'สถานะธุรกิจ',
    placeholder: 'สถานะธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'newly_registered', label: 'ลูกค้าที่เพิ่งลงทะเบียนใหม่ในระบบ' },
      { value: 'active', label: 'ลูกค้าที่ใช้งานอย่างต่อเนื่อง' },
      { value: 'loyal_customer', label: 'ลูกค้าที่มีความภักดีต่อระบบ' },
      { value: 'at_risk', label: 'ลูกค้าที่อาจจะเสี่ยงต่อการหยุดใช้งาน' },
      { value: 'churned', label: 'ลูกค้าที่ได้หยุดใช้บริการหรือยกเลิกบัญชี' },
    ],
    defaultValue: 'newly_registered',
    rule: [{ required: true, message: 'กรุณาเลือกสถานะธุรกิจ!' }],
  },
  {
    name: ['branch', 'nameTh'],
    label: 'ชื่อสาขา (ภาษาไทย)',
    placeholder: 'ชื่อสาขา (ภาษาไทย)',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกชื่อสาขา (ภาษาไทย)!' }],
    errorUniqMessage: 'ไม่สามารถใช้งานชื่อนี้ได้',
    isName: true,
  },
  {
    name: ['branch', 'nameEn'],
    label: 'ชื่อกิจการ (English)',
    placeholder: 'ชื่อกิจการ (English)',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกชื่อสาขา (English)!' }],
    errorUniqMessage: 'ไม่สามารถใช้งานชื่อนี้ได้',
    isName: true,
  },
  {
    name: ['branch', 'taxId'],
    label: 'เลขทะเบียน 13 หลัก',
    placeholder: 'เลขทะเบียน 13 หลัก',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'LengthInput',
    maxLength: 13,
    rule: [{ required: true, message: 'กรุณากรอกเลขทะเบียน 13 หลัก!' }],
    errorUniqMessage: 'ไม่สามารถใช้งานเลขทะเบียน13หลักนี้ได้',
  },
  {
    name: ['branch', 'descriptionsTh'],
    label: 'คำอธิบายธุรกิจ (ภาษาไทย)',
    placeholder: 'คำอธิบายธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextAreaFormField',
  },
  {
    name: ['branch', 'descriptionsEn'],
    label: 'คำอธิบายธุรกิจ (English)',
    placeholder: 'คำอธิบายธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextAreaFormField',
  },

  {
    name: ['branch', 'openingDate'],
    label: 'วันที่จดทะเบียน',
    placeholder: 'วันที่จดทะเบียน',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'DatePickerFormField',
  },
  {
    name: ['branch', 'registerVat'],
    label: 'จดทะเบียนภาษีมูลค่าเพิ่ม',
    placeholder: 'จดทะเบียนภาษีมูลค่าเพิ่ม',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SwitchFormField',
    rule: [
      {
        required: true,
        message: 'กรุณาเลือกว่าจดทะเบียนภาษีมูลค่าเพิ่มหรือไม่!',
      },
    ],
    checkedText: 'จด',
    unCheckedText: 'ไม่ได้จด',
  },
  {
    name: ['branch', 'websiteUrl'],
    label: 'เว็ปไซต์สำนักงาน',
    placeholder: 'เว็ปไซต์สำนักงาน',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['branch', 'domainName'],
    label: 'ชื่อโดเมน',
    placeholder: 'ชื่อโดเมน ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [
      { required: true, message: 'กรุณากรอกชื่อโดเมน!' },
      {
        pattern: /^(?!-)([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}(?<!-)$/,
        message:
          'กรุณากรอกชื่อโดเมนให้ถูกต้อง เช่น utotech.com หรือ utotech.co.th',
      },
    ],
  },
  {
    label: 'ข้อมูลช่องทางการติดต่อขององค์กร',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'SectionLabelForm',
  },
  {
    name: ['branch', 'contactName'],
    label: 'รายชื่อผู้ติดต่อ',
    placeholder: 'รายชื่อผู้ติดต่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกรายชื่อผู้ติดต่อ!' }],
  },
  {
    name: ['branch', 'contactPhone'],
    label: 'เบอร์โทรศัพท์ติดต่อ',
    placeholder: 'เบอร์โทรศัพท์ติดต่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'PhoneInput',
    rule: [{ required: true, message: 'กรุณากรอกเบอร์โทรศัพท์ติดต่อ!' }],
  },
  {
    name: ['branch', 'contactEmail'],
    label: 'อีเมลติดต่อ',
    placeholder: 'อีเมลติดต่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกเบอร์อีเมลติดต่อ!' }],
  },
  {
    name: ['branch', 'contactWebsite'],
    label: 'เว็บไซต์ติดต่อ',
    placeholder: 'เว็บไซต์ติดต่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['branch', 'contactFacebook'],
    label: 'Facebook',
    placeholder: 'Facebook',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['branch', 'contactLine'],
    label: 'Line ID',
    placeholder: 'line Id',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },

  {
    name: ['branch', 'contactWhatsapp'],
    label: 'WhatsApp',
    placeholder: 'WhatsApp',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['branch', 'contactNote'],
    label: 'ข้อมูลการติดต่อ',
    placeholder: 'ข้อมูลการติดต่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    label: 'ข้อมูลที่อยู่สาขา',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'SectionLabelForm',
  },
  {
    name: ['branch', 'address', 'name'],
    label: 'ชื่อที่อยู่',
    placeholder: 'ชื่อที่อยู่',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกชื่อที่อยู่!' }],
  },
  {
    name: ['branch', 'address', 'city'],
    label: 'เมือง',
    placeholder: 'เมือง',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกชื่อเมือง!' }],
  },
  {
    name: ['branch', 'address', 'province'],
    label: 'จังหวัด',
    placeholder: 'จังหวัด',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกชื่อจังหวัด!' }],
  },
  {
    name: ['branch', 'address', 'postalCode'],
    label: 'รหัสไปรษณีย์',
    placeholder: 'รหัสไปรษณีย์',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกรหัสไปรษณีย์!' }],
  },

  {
    name: ['branch', 'address', 'roomNo'],
    label: 'เลขห้อง',
    placeholder: 'เลขห้อง',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: ['branch', 'address', 'floorNo'],
    label: 'ชั้นที่อยู่',
    placeholder: 'ชั้นที่อยู่',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: ['branch', 'address', 'village'],
    label: 'หมู่บ้าน',
    placeholder: 'หมู่บ้าน',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: ['branch', 'address', 'villageNo'],
    label: 'เลขหมู่บ้าน',
    placeholder: 'เลขหมู่บ้าน',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: ['branch', 'address', 'houseNo'],
    label: 'บ้านเลขที่',
    placeholder: 'บ้านเลขที่',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: ['branch', 'address', 'alley'],
    label: 'ตรอก',
    placeholder: 'ตรอก',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: ['branch', 'address', 'road'],
    label: 'ถนน',
    placeholder: 'ถนน',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: ['branch', 'address', 'building'],
    label: 'อาคาร',
    placeholder: 'อาคาร',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },

  {
    name: ['branch', 'address', 'nation'],
    label: 'ประเทศ',
    placeholder: 'ประเทศ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },

  {
    name: ['branch', 'address', 'district'],
    label: 'เขต/อำเภอ',
    placeholder: 'เขต/อำเภอ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['branch', 'address', 'subDistrict'],
    label: 'แขวง/ตำบล',
    placeholder: 'แขวง/ตำบล',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },

  {
    name: ['branch', 'address', 'note'],
    label: 'หมายเหตุ',
    placeholder: 'หมายเหตุ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextAreaFormField',
  },
];

/*Setting Section*/
export const renderCreateSettingForm = [
  {
    label: 'เพิ่มผู้ใช้งานองค์กร',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'SectionLabelForm',
  },
  {
    name: ['organization', 'user', 'email'],
    label: 'อีเมล',
    placeholder: 'อีเมล',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [
      { required: true, message: 'กรุณากรอกอีเมลผู้ใช้งาน!' },
      {
        pattern: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
        message: 'กรุณากรอกอีเมลที่ถูกต้อง!',
      },
    ],
  },
  {
    name: ['organization', 'user', 'password'],
    label: 'รหัสผ่าน',
    placeholder: 'รหัสผ่าน',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกรหัสผ่านผู้ใช้งาน!' }],
  },

  {
    name: ['organization', 'user', 'profile', 'firstName'],
    label: 'ชื่อ',
    placeholder: 'ชื่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกชื่อผู้ใช้งาน!' }],
  },
  {
    name: ['organization', 'user', 'profile', 'lastName'],
    label: 'นามสกุล',
    placeholder: 'นามสกุล',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['organization', 'user', 'userName'],
    label: 'ชื่อผู้ใช้',
    placeholder: 'ชื่อผู้ใช้',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['organization', 'user', 'profile', 'birthDate'],
    label: 'วันเกิด',
    placeholder: 'วันเกิด',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'DatePickerFormField',
  },
  {
    name: ['organization', 'user', 'profile', 'phone'],
    label: 'เบอร์โทรศัพท์ติดต่อ',
    placeholder: 'เบอร์โทรศัพท์ติดต่อ ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'PhoneInput',
  },
  {
    label: 'ตั้งค่าระบบขององค์กร',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'SectionLabelForm',
  },
  {
    name: ['organization', 'setting', 'defaultLanguage'],
    label: 'ภาษา',
    placeholder: 'ภาษา',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'th', label: 'ภาษาไทย' },
      { value: 'en', label: 'English' },
    ],
    defaultValue: 'th',
    rule: [{ required: true, message: 'กรุณาเลือกภาษา!' }],
  },

  {
    name: ['organization', 'setting', 'theme'],
    label: 'ธีมสี',
    placeholder: 'ธีมสี',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'light', label: 'สว่าง' },
      { value: 'dark', label: 'มืด' },
    ],
    defaultValue: 'light',
    rule: [{ required: true, message: 'กรุณาเลือกธีมสี!' }],
  },
  {
    name: ['organization', 'setting', 'textDisplay'],
    label: 'ขนาดตัวอักษร',
    placeholder: 'ขนาดตัวอักษร',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'large', label: 'ขนาดใหญ่' },
      { value: 'normal', label: 'ปกติ' },
      { value: 'small', label: 'ขนาดเล็ก' },
    ],
    defaultValue: 'normal',
    rule: [{ required: true, message: 'กรุณาเลือกขนาดตัวอักษร!' }],
  },
];

export const renderCreateSettingฺBranchForm = [
  {
    label: 'เพิ่มผู้ใช้งานสาขา',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'SectionLabelForm',
  },
  {
    name: ['branch', 'user', 'email'],
    label: 'อีเมล',
    placeholder: 'อีเมล',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [
      { required: true, message: 'กรุณากรอกอีเมลผู้ใช้งาน!' },
      {
        pattern: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
        message: 'กรุณากรอกอีเมลที่ถูกต้อง!',
      },
    ],
  },
  {
    name: ['branch', 'user', 'password'],
    label: 'รหัสผ่าน',
    placeholder: 'รหัสผ่าน',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกรหัสผ่านผู้ใช้งาน!' }],
  },

  {
    name: ['branch', 'user', 'profile', 'firstName'],
    label: 'ชื่อ',
    placeholder: 'ชื่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกชื่อผู้ใช้งาน!' }],
  },
  {
    name: ['branch', 'user', 'profile', 'lastName'],
    label: 'นามสกุล',
    placeholder: 'นามสกุล',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['branch', 'user', 'userName'],
    label: 'ชื่อผู้ใช้',
    placeholder: 'ชื่อผู้ใช้',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: ['branch', 'user', 'profile', 'birthDate'],
    label: 'วันเกิด',
    placeholder: 'วันเกิด',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'DatePickerFormField',
  },
  {
    name: ['branch', 'user', 'profile', 'phone'],
    label: 'เบอร์โทรศัพท์ติดต่อ',
    placeholder: 'เบอร์โทรศัพท์ติดต่อ ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'PhoneInput',
  },
  {
    label: 'ตั้งค่าระบบของสาขา',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'SectionLabelForm',
  },
  {
    name: ['branch', 'setting', 'defaultLanguage'],
    label: 'ภาษา',
    placeholder: 'ภาษา',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'th', label: 'ภาษาไทย' },
      { value: 'en', label: 'English' },
    ],
    defaultValue: 'th',
    rule: [{ required: true, message: 'กรุณาเลือกภาษา!' }],
  },

  {
    name: ['branch', 'setting', 'theme'],
    label: 'ธีมสี',
    placeholder: 'ธีมสี',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'light', label: 'สว่าง' },
      { value: 'dark', label: 'มืด' },
    ],
    defaultValue: 'light',
    rule: [{ required: true, message: 'กรุณาเลือกธีมสี!' }],
  },
  {
    name: ['branch', 'setting', 'textDisplay'],
    label: 'ขนาดตัวอักษร',
    placeholder: 'ขนาดตัวอักษร',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'large', label: 'ขนาดใหญ่' },
      { value: 'normal', label: 'ปกติ' },
      { value: 'small', label: 'ขนาดเล็ก' },
    ],
    defaultValue: 'normal',
    rule: [{ required: true, message: 'กรุณาเลือกขนาดตัวอักษร!' }],
  },
];

export const renderEditForm = [
  //FIXME:add upload logo url

  {
    label: 'ข้อมูลองค์กร',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'SectionLabelForm',
  },
  {
    label: 'รูปภาพองค์กร',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'UploadFile',
  },
  {
    name: 'active',
    label: 'ปิดองค์กร',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'ActiveCard',
    title: 'ปิดองค์กร',
    description:
      'ใช้สำหรับการปิดหรือยุติการทำงานขององค์กรในระบบหรือเว็บไซต์ ซึ่งอาจรวมถึงการปิดการใช้งานบัญชีองค์กร',
    rule: [{ required: true, message: 'กรุณาเลือกเปิดปิดองค์กร!' }],
  },
  {
    name: 'status',
    label: 'สถานะธุรกิจ',
    placeholder: 'สถานะธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'newly_registered', label: 'ลูกค้าที่เพิ่งลงทะเบียนใหม่ในระบบ' },
      { value: 'active', label: 'ลูกค้าที่ใช้งานอย่างต่อเนื่อง' },
      { value: 'loyal_customer', label: 'ลูกค้าที่มีความภักดีต่อระบบ' },
      { value: 'at_risk', label: 'ลูกค้าที่อาจจะเสี่ยงต่อการหยุดใช้งาน' },
      { value: 'churned', label: 'ลูกค้าที่ได้หยุดใช้บริการหรือยกเลิกบัญชี' },
    ],
    defaultValue: 'newly_registered',
    rule: [{ required: true, message: 'กรุณาเลือกสถานะธุรกิจ!' }],
  },

  {
    name: 'fromType',
    label: 'ประเภทธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'RadioFormField',
    options: [
      { value: 'ordinary_person', label: 'บุคคลธรรมดา' },
      { value: 'juristic_person', label: 'นิติบุคคล' },
    ],
    defaultValue: 'ordinary_person',
    rule: [{ required: true, message: 'กรุณาเลือกประเภทธุรกิจ!' }],
  },
  {
    name: 'type',
    label: 'รูปแบบธุรกิจ',
    placeholder: 'รูปแบบธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'company_limited', label: 'บริษัทจำกัด' },
      { value: 'public_company_limited', label: 'บริษัทมหาชนจำกัด' },
      { value: 'limited_partnership', label: 'ห้างหุ้นส่วนจำกัด' },
      { value: 'foundation', label: 'มูลนิธิ' },
      { value: 'association', label: 'สมาคม' },
      { value: 'joint_venture', label: 'กิจการร่วมค้า' },
      { value: 'others', label: 'อื่นๆ' },
    ],
    rule: [{ required: true, message: 'กรุณาเลือกรูปแบบธุรกิจ!' }],
  },
  {
    name: 'nameTh',
    label: 'ชื่อกิจการ (ภาษาไทย)',
    placeholder: 'ชื่อกิจการ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกชื่อกิจการ (ภาษาไทย)!' }],
    isName: true,
  },
  {
    name: 'nameEn',
    label: 'ชื่อกิจการ (English)',
    placeholder: 'ชื่อกิจการ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกชื่อกิจการ (English)!' }],
    isName: true,
  },
  {
    name: 'taxId',
    label: 'เลขทะเบียน 13 หลัก',
    placeholder: 'เลขทะเบียน 13 หลัก',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'LengthInput',
    maxLength: 13,
    rule: [{ required: true, message: 'กรุณากรอกเลขทะเบียน 13 หลัก!' }],
  },
  {
    name: 'registerVat',
    label: 'จดทะเบียนภาษีมูลค่าเพิ่ม',
    placeholder: 'จดทะเบียนภาษีมูลค่าเพิ่ม',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SwitchFormField',
    rule: [
      {
        required: true,
        message: 'กรุณาเลือกว่าจดทะเบียนภาษีมูลค่าเพิ่มหรือไม่!',
      },
    ],
    checkedText: 'จด',
    unCheckedText: 'ไม่ได้จด',
  },

  {
    name: 'descriptionsTh',
    label: 'คำอธิบายธุรกิจ (ภาษาไทย)',
    placeholder: 'คำอธิบายธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextAreaFormField',
  },
  {
    name: 'descriptionsEn',
    label: 'คำอธิบายธุรกิจ (English)',
    placeholder: 'คำอธิบายธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextAreaFormField',
  },

  {
    name: 'openingDate',
    label: 'วันที่จดทะเบียน',
    placeholder: 'วันที่จดทะเบียน',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'DatePickerFormField',
  },
  {
    name: 'websiteUrl',
    label: 'เว็ปไซต์สำนักงาน',
    placeholder: 'เว็ปไซต์สำนักงาน',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },

  /*Setting Section*/

  {
    name: ['setting', 'defaultLanguage'],
    label: 'ภาษา',
    placeholder: 'ภาษา',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'th', label: 'ภาษาไทย' },
      { value: 'en', label: 'English' },
    ],
    defaultValue: 'th',
    rule: [{ required: true, message: 'กรุณาเลือกภาษา!' }],
  },
  {
    name: ['setting', 'domainName'],
    label: 'ชื่อโดเมน',
    placeholder: 'ชื่อโดเมน ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกชื่อโดเมน!' }],
  },
  {
    name: ['setting', 'theme'],
    label: 'ธีมสี',
    placeholder: 'ธีมสี',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'light', label: 'สว่าง' },
      { value: 'dark', label: 'มืด' },
    ],
    defaultValue: 'light',
  },
  {
    name: ['setting', 'textDisplay'],
    label: 'ตัวอักษร',
    placeholder: 'ตัวอักษร',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'large', label: 'ขนาดใหญ่' },
      { value: 'normal', label: 'ปกติ' },
      { value: 'small', label: 'ขนาดเล็ก' },
    ],
    defaultValue: 'normal',
  },

  {
    label: 'ข้อมูลช่องทางการติดต่อ',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'SectionLabelForm',
  },

  {
    name: 'contactPhone',
    label: 'เบอร์โทรศัพท์ติดต่อ',
    placeholder: 'เบอร์โทรศัพท์ติดต่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'PhoneInput',
    rule: [{ required: true, message: 'กรุณากรอกเบอร์โทรศัพท์ติดต่อ!' }],
  },
  {
    name: 'contactEmail',
    label: 'อีเมลติดต่อ',
    placeholder: 'อีเมลติดต่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกเบอร์อีเมลติดต่อ!' }],
  },
  {
    name: 'contactWebsite',
    label: 'เว็บไซต์ติดต่อ',
    placeholder: 'เว็บไซต์ติดต่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'businessEmail',
    label: 'อีเมลสำนักงาน',
    placeholder: 'อีเมลสำนักงาน',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },

  {
    name: 'contactFacebook',
    label: 'Facebook',
    placeholder: 'Facebook',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'contactLine',
    label: 'Line ID',
    placeholder: 'line Id',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },

  {
    name: 'contactWhatsapp',
    label: 'WhatsApp',
    placeholder: 'WhatsApp',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'contactNote',
    label: 'ข้อมูลการติดต่อ',
    placeholder: 'ข้อมูลการติดต่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    label: 'ข้อมูลที่อยู่',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'SectionLabelForm',
  },
];

export const renderSettingData = [
  {
    label: 'ข้อมูลองค์กร',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'SectionLabelForm',
  },
  {
    label: 'รูปภาพองค์กร',
    col: { xs: 24, sm: 24, md: 6, lg: 6, xl: 6 },
    type: 'UploadFile',
  },
  {
    name: 'active',
    label: 'ปิดองค์กร',
    col: { xs: 24, sm: 24, md: 18, lg: 18, xl: 18 },
    type: 'ActiveCard',
    title: 'ปิดองค์กร',
    description:
      'ใช้สำหรับการปิดหรือยุติการทำงานขององค์กรในระบบหรือเว็บไซต์ ซึ่งอาจรวมถึงการปิดการใช้งานบัญชีองค์กร',
    rule: [{ required: true, message: 'กรุณาเลือกเปิดปิดองค์กร!' }],
  },
  {
    name: 'fromType',
    label: 'ประเภทธุรกิจ',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'RadioFormField',
    options: [
      { value: 'ordinary_person', label: 'บุคคลธรรมดา' },
      { value: 'juristic_person', label: 'นิติบุคคล' },
    ],
    defaultValue: 'ordinary_person',
    rule: [{ required: true, message: 'กรุณาเลือกประเภทธุรกิจ!' }],
  },
  {
    name: 'status',
    label: 'สถานะธุรกิจ',
    placeholder: 'สถานะธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'newly_registered', label: 'ลูกค้าที่เพิ่งลงทะเบียนใหม่ในระบบ' },
      { value: 'active', label: 'ลูกค้าที่ใช้งานอย่างต่อเนื่อง' },
      { value: 'loyal_customer', label: 'ลูกค้าที่มีความภักดีต่อระบบ' },
      { value: 'at_risk', label: 'ลูกค้าที่อาจจะเสี่ยงต่อการหยุดใช้งาน' },
      { value: 'churned', label: 'ลูกค้าที่ได้หยุดใช้บริการหรือยกเลิกบัญชี' },
    ],
    defaultValue: 'newly_registered',
    rule: [{ required: true, message: 'กรุณาเลือกสถานะธุรกิจ!' }],
  },

  {
    name: 'type',
    label: 'รูปแบบธุรกิจ',
    placeholder: 'รูปแบบธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'Taxpayer', label: 'บุคคลธรรมดา' },
      { value: 'OrdinaryPartnership', label: 'ห้างหุ้นส่วนสามัญ' },
      { value: 'Shop', label: 'ร้านค้า' },
      { value: 'BodyOfPerson', label: 'คณะบุคคล' },
      { value: 'company_limited', label: 'บริษัทจำกัด' },
      { value: 'public_company_limited', label: 'บริษัทมหาชนจำกัด' },
      { value: 'limited_partnership', label: 'ห้างหุ้นส่วนจำกัด' },
      { value: 'foundation', label: 'มูลนิธิ' },
      { value: 'association', label: 'สมาคม' },
      { value: 'joint_venture', label: 'กิจการร่วมค้า' },
      { value: 'others', label: 'อื่นๆ' },
    ],
    rule: [{ required: true, message: 'กรุณาเลือกรูปแบบธุรกิจ!' }],
  },
  {
    name: 'nameTh',
    label: 'ชื่อกิจการ (ภาษาไทย)',
    placeholder: 'ชื่อกิจการ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกชื่อกิจการ (ภาษาไทย)!' }],
    isName: true,
    errorUniqMessage: 'ไม่สามารถใช้งานชื่อนี้ได้',
  },
  {
    name: 'nameEn',
    label: 'ชื่อกิจการ (English)',
    placeholder: 'ชื่อกิจการ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกชื่อกิจการ (English)!' }],
    isName: true,
    errorUniqMessage: 'ไม่สามารถใช้งานชื่อนี้ได้',
  },

  {
    name: 'taxId',
    label: 'เลขทะเบียน 13 หลัก',
    placeholder: 'เลขทะเบียน 13 หลัก',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'LengthInput',
    maxLength: 13,
    rule: [{ required: true, message: 'กรุณากรอกเลขทะเบียน 13 หลัก!' }],
    errorUniqMessage: 'ไม่สามารถใช้งานเลขทะเบียน13หลักนี้ได้',
  },

  {
    name: 'descriptionsTh',
    label: 'คำอธิบายธุรกิจ (ภาษาไทย)',
    placeholder: 'คำอธิบายธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextAreaFormField',
  },
  {
    name: 'descriptionsEn',
    label: 'คำอธิบายธุรกิจ (English)',
    placeholder: 'คำอธิบายธุรกิจ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextAreaFormField',
  },

  {
    name: 'openingDate',
    label: 'วันที่จดทะเบียน',
    placeholder: 'วันที่จดทะเบียน',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'DatePickerFormField',
  },
  {
    name: 'registerVat',
    label: 'จดทะเบียนภาษีมูลค่าเพิ่ม',
    placeholder: 'จดทะเบียนภาษีมูลค่าเพิ่ม',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SwitchFormField',
    rule: [
      {
        required: true,
        message: 'กรุณาเลือกว่าจดทะเบียนภาษีมูลค่าเพิ่มหรือไม่!',
      },
    ],
    checkedText: 'จด',
    unCheckedText: 'ไม่ได้จด',
  },
  {
    name: 'websiteUrl',
    label: 'เว็ปไซต์สำนักงาน',
    placeholder: 'เว็ปไซต์สำนักงาน',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'domainName',
    label: 'ชื่อโดเมน',
    placeholder: 'ชื่อโดเมน ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกชื่อโดเมน!' }],
  },

  {
    label: 'ข้อมูลช่องทางการติดต่อ',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'SectionLabelForm',
  },
  {
    name: 'contactName',
    label: 'รายชื่อผู้ติดต่อ',
    placeholder: 'รายชื่อผู้ติดต่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกรายชื่อผู้ติดต่อ!' }],
  },
  {
    name: 'contactPhone',
    label: 'เบอร์โทรศัพท์ติดต่อ',
    placeholder: 'เบอร์โทรศัพท์ติดต่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'PhoneInput',
    rule: [{ required: true, message: 'กรุณากรอกเบอร์โทรศัพท์ติดต่อ!' }],
  },
  {
    name: 'contactEmail',
    label: 'อีเมลติดต่อ',
    placeholder: 'อีเมลติดต่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกเบอร์อีเมลติดต่อ!' }],
  },
  {
    name: 'contactWebsite',
    label: 'เว็บไซต์ติดต่อ',
    placeholder: 'เว็บไซต์ติดต่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'contactFacebook',
    label: 'Facebook',
    placeholder: 'Facebook',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'contactLine',
    label: 'Line ID',
    placeholder: 'line Id',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },

  {
    name: 'contactWhatsapp',
    label: 'WhatsApp',
    placeholder: 'WhatsApp',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'contactNote',
    label: 'ข้อมูลการติดต่อ',
    placeholder: 'ข้อมูลการติดต่อ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
];

export const renderAddressSetting = [
  {
    label: 'ข้อมูลที่อยู่องค์กร',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'SectionLabelForm',
  },
  {
    name: 'name',
    label: 'ชื่อที่อยู่',
    placeholder: 'ชื่อที่อยู่',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกชื่อที่อยู่!' }],
  },
  {
    name: 'city',
    label: 'เมือง',
    placeholder: 'เมือง',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกชื่อเมือง!' }],
  },
  {
    name: 'province',
    label: 'จังหวัด',
    placeholder: 'จังหวัด',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกชื่อจังหวัด!' }],
  },
  {
    name: 'postalCode',
    label: 'รหัสไปรษณีย์',
    placeholder: 'รหัสไปรษณีย์',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกรหัสไปรษณีย์!' }],
  },
  {
    name: 'roomNo',
    label: 'เลขห้อง',
    placeholder: 'เลขห้อง',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: 'floorNo',
    label: 'ชั้นที่อยู่',
    placeholder: 'ชั้นที่อยู่',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: 'village',
    label: 'หมู่บ้าน',
    placeholder: 'หมู่บ้าน',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: 'villageNo',
    label: 'เลขหมู่บ้าน',
    placeholder: 'เลขหมู่บ้าน',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: 'houseNo',
    label: 'บ้านเลขที่',
    placeholder: 'บ้านเลขที่',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: 'alley',
    label: 'ตรอก',
    placeholder: 'ตรอก',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: 'road',
    label: 'ถนน',
    placeholder: 'ถนน',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: 'building',
    label: 'อาคาร',
    placeholder: 'อาคาร',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },

  {
    name: 'nation',
    label: 'ประเทศ',
    placeholder: 'ประเทศ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },

  {
    name: 'district',
    label: 'เขต/อำเภอ',
    placeholder: 'เขต/อำเภอ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'subDistrict',
    label: 'แขวง/ตำบล',
    placeholder: 'แขวง/ตำบล',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },

  {
    name: 'note',
    label: 'หมายเหตุ',
    placeholder: 'หมายเหตุ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextAreaFormField',
  },
];

export const renderSystemSetting = [
  {
    label: 'ตั้งค่าระบบ',
    col: { xs: 24, sm: 24, md: 24, lg: 24, xl: 24 },
    type: 'SectionLabelForm',
  },
  {
    name: 'defaultLanguage',
    label: 'ภาษา',
    placeholder: 'ภาษา',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'th', label: 'ภาษาไทย' },
      { value: 'en', label: 'English' },
    ],
    defaultValue: 'th',
    rule: [{ required: true, message: 'กรุณาเลือกภาษา!' }],
  },
  {
    name: 'theme',
    label: 'ธีมสี',
    placeholder: 'ธีมสี',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'light', label: 'สว่าง' },
      { value: 'dark', label: 'มืด' },
    ],
    defaultValue: 'light',
    rule: [{ required: true, message: 'กรุณาเลือกธีมสี!' }],
  },
  {
    name: 'textDisplay',
    label: 'ขนาดตัวอักษร',
    placeholder: 'ขนาดตัวอักษร',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'large', label: 'ขนาดใหญ่' },
      { value: 'normal', label: 'ปกติ' },
      { value: 'small', label: 'ขนาดเล็ก' },
    ],
    defaultValue: 'normal',
    rule: [{ required: true, message: 'กรุณาเลือกขนาดตัวอักษร!' }],
  },
];

export const renderAddress = [
  {
    name: 'name',
    label: 'ชื่อที่อยู่',
    placeholder: 'ชื่อที่อยู่',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกชื่อที่อยู่!' }],
  },
  {
    name: 'city',
    label: 'เมือง',
    placeholder: 'เมือง',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกชื่อเมือง!' }],
  },
  {
    name: 'province',
    label: 'จังหวัด',
    placeholder: 'จังหวัด',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกชื่อจังหวัด!' }],
  },
  {
    name: 'postalCode',
    label: 'รหัสไปรษณีย์',
    placeholder: 'รหัสไปรษณีย์',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
    rule: [{ required: true, message: 'กรุณากรอกรหัสไปรษณีย์!' }],
  },
  {
    name: 'roomNo',
    label: 'เลขห้อง',
    placeholder: 'เลขห้อง',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: 'floorNo',
    label: 'ชั้นที่อยู่',
    placeholder: 'ชั้นที่อยู่',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: 'village',
    label: 'หมู่บ้าน',
    placeholder: 'หมู่บ้าน',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: 'villageNo',
    label: 'เลขหมู่บ้าน',
    placeholder: 'เลขหมู่บ้าน',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: 'houseNo',
    label: 'บ้านเลขที่',
    placeholder: 'บ้านเลขที่',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: 'alley',
    label: 'ตรอก',
    placeholder: 'ตรอก',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: 'road',
    label: 'ถนน',
    placeholder: 'ถนน',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },
  {
    name: 'building',
    label: 'อาคาร',
    placeholder: 'อาคาร',
    col: { xs: 12, sm: 12, md: 6, lg: 6, xl: 6 },
    type: 'TextboxFormField',
  },

  {
    name: 'nation',
    label: 'ประเทศ',
    placeholder: 'ประเทศ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },

  {
    name: 'district',
    label: 'เขต/อำเภอ',
    placeholder: 'เขต/อำเภอ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },
  {
    name: 'subDistrict',
    label: 'แขวง/ตำบล',
    placeholder: 'แขวง/ตำบล',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextboxFormField',
  },

  {
    name: 'note',
    label: 'หมายเหตุ',
    placeholder: 'หมายเหตุ',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'TextAreaFormField',
  },
];

export const renderSetting = [
  {
    name: 'defaultLanguage',
    label: 'ภาษา',
    placeholder: 'ภาษา',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'th', label: 'ภาษาไทย' },
      { value: 'en', label: 'English' },
    ],
    defaultValue: 'th',
    rule: [{ required: true, message: 'กรุณาเลือกภาษา!' }],
  },
  {
    name: 'theme',
    label: 'ธีมสี',
    placeholder: 'ธีมสี',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'light', label: 'สว่าง' },
      { value: 'dark', label: 'มืด' },
    ],
    defaultValue: 'light',
    rule: [{ required: true, message: 'กรุณาเลือกธีมสี!' }],
  },
  {
    name: 'textDisplay',
    label: 'ขนาดตัวอักษร',
    placeholder: 'ขนาดตัวอักษร',
    col: { xs: 24, sm: 24, md: 12, lg: 12, xl: 12 },
    type: 'SelectFormField',
    options: [
      { value: 'large', label: 'ขนาดใหญ่' },
      { value: 'normal', label: 'ปกติ' },
      { value: 'small', label: 'ขนาดเล็ก' },
    ],
    defaultValue: 'normal',
    rule: [{ required: true, message: 'กรุณาเลือกขนาดตัวอักษร!' }],
  },
];
