import vine from '@vinejs/vine';

const settingSchema = vine.object({
  active: vine.boolean(),
  defaultLanguage: vine.enum(['TH', 'EN', 'JP']),
  textDisplay: vine.string().optional(),
  theme: vine.enum(['light', 'dark']).optional(),
  openDays: vine.array(
    vine.object({
      day: vine.array(
        vine.enum([
          'Sunday',
          'Monday',
          'Tuesday',
          'Wednesday',
          'Thursday',
          'Friday',
          'Saturday',
        ]),
      ),
      openTime: vine.string().regex(/^\d{2}:\d{2}$/),
      closeTime: vine.string().regex(/^\d{2}:\d{2}$/),
    }),
  ),
});

const addressSchema = vine.object({
  active: vine.boolean(),
  language: vine.string(),
  isMain: vine.boolean(),
  name: vine.string(),
  city: vine.string().optional(),
  province: vine.string().optional(),
  postalCode: vine.string().maxLength(5).optional(),
  roomNo: vine.string().optional(),
  floorNo: vine.string().optional(),
  village: vine.string().optional(),
  villageNo: vine.string().optional(),
  houseNo: vine.string().optional(),
  alley: vine.string().optional(),
  road: vine.string().optional(),
  building: vine.string().optional(),
  nation: vine.string().optional(),
  district: vine.string().optional(),
  subDistrict: vine.string().optional(),
  note: vine.string().optional(),
});

const profileSchema = vine.object({
  firstName: vine.string(),
  lastName: vine.string().optional(),
  birthDate: vine.string().optional(),
  phone: vine.string().maxLength(15).optional(),
});

const userSchema = vine.object({
  active: vine.boolean(),
  status: vine.string(),
  email: vine.string().email(),
  password: vine.string(),
  userName: vine.string().optional(),
  profile: profileSchema.clone(),
});

export const schemaUpdateOrg = vine.object({
  nameTh: vine.string(),
  nameEn: vine.string(),
  taxId: vine.string(),
  active: vine.boolean(),
  status: vine.enum([
    'NewlyRegistered',
    'ActiveUser',
    'LoyalCustomer',
    'AtRisk',
    'Churned',
  ]),
  fromType: vine.enum(['OrdinaryPerson', 'JuristicPerson']),
  type: vine.enum([
    'human',
    'ordinary_partnership',
    'shop',
    'bop',
    'CompanyLimited',
    'PublicCompanyLimited',
    'LimitedPartnership',
    'Foundation',
    'Association',
    'JointVenture',
    'Others',
  ]),
  descriptionsTh: vine.string().optional(),
  descriptionsEn: vine.string().optional(),
  registerVat: vine.boolean(),
  openingDate: vine.string().optional(),
  websiteUrl: vine.string().optional(),
  domainName: vine.string(),
  contactName: vine.string(),
  contactEmail: vine.string().email(),
  contactPhone: vine.string().maxLength(15),
  contactWebsite: vine.string().optional(),
  businessEmail: vine.string().email().optional(),
  contactFacebook: vine.string().optional(),
  contactLine: vine.string().optional(),
  contactWhatsapp: vine.string().optional(),
  contactNote: vine.string().optional(),
  // addresses: addressesSchema.clone(),
  // setting: settingSchema.clone(),
});

export const schemaCreateOrg = vine.object({
  organization: vine.object({
    active: vine.boolean(),
    fromType: vine.enum(['OrdinaryPerson', 'JuristicPerson']),
    status: vine.enum([
      'NewlyRegistered',
      'ActiveUser',
      'LoyalCustomer',
      'AtRisk',
      'Churned',
    ]),
    type: vine.enum([
      'human',
      'ordinary_partnership',
      'shop',
      'bop',
      'CompanyLimited',
      'PublicCompanyLimited',
      'LimitedPartnership',
      'Foundation',
      'Association',
      'JointVenture',
      'Others',
    ]),
    logoUrl: vine.string().optional(),
    nameTh: vine.string(),
    nameEn: vine.string(),
    taxId: vine.string(),
    descriptionsTh: vine.string().optional(),
    descriptionsEn: vine.string().optional(),
    openingDate: vine.string().optional(),
    registerVat: vine.boolean(),
    websiteUrl: vine.string().optional(),
    domainName: vine.string(),
    contactName: vine.string(),
    contactPhone: vine.string().maxLength(15),
    contactEmail: vine.string().email(),
    contactWebsite: vine.string().optional(),
    contactFacebook: vine.string().optional(),
    contactLine: vine.string().optional(),
    contactWhatsapp: vine.string().optional(),
    contactNote: vine.string().optional(),
    address: addressSchema.clone(),
    user: userSchema.clone(),
    setting: settingSchema.clone(),
  }),
  branch: vine.object({
    active: vine.boolean(),
    fromType: vine.enum(['OrdinaryPerson', 'JuristicPerson']),
    status: vine.enum([
      'NewlyRegistered',
      'ActiveUser',
      'LoyalCustomer',
      'AtRisk',
      'Churned',
    ]),
    type: vine.enum([
      'human',
      'ordinary_partnership',
      'shop',
      'bop',
      'CompanyLimited',
      'PublicCompanyLimited',
      'LimitedPartnership',
      'Foundation',
      'Association',
      'JointVenture',
      'Others',
    ]),
    logoUrl: vine.string().optional(),
    nameTh: vine.string(),
    nameEn: vine.string(),
    taxId: vine.string(),
    descriptionsTh: vine.string().optional(),
    descriptionsEn: vine.string().optional(),
    openingDate: vine.string().optional(),
    registerVat: vine.boolean(),
    websiteUrl: vine.string().optional(),
    domainName: vine.string(),
    contactName: vine.string(),
    contactPhone: vine.string().maxLength(15),
    contactEmail: vine.string().email(),
    contactWebsite: vine.string().optional(),
    contactFacebook: vine.string().optional(),
    contactLine: vine.string().optional(),
    contactWhatsapp: vine.string().optional(),
    contactNote: vine.string().optional(),
    address: addressSchema.clone(),
    user: userSchema.clone(),
    setting: settingSchema.clone(),
  }),
});
