name: Build Checked

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Get the Git branch version
        id: get_version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Configure Docker client
        run: gcloud auth configure-docker ${{ secrets.GCP_IMAGE_REGISTRY }} --quiet

      - name: Build Docker image
        env:
          APP_IMAGE: ${{ secrets.GCP_IMAGE_REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/${{ github.event.repository.name }}
          APP_VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          docker build -t $APP_IMAGE:$APP_VERSION .

      - name: Push Docker image to Artifact Registry
        env:
          APP_IMAGE: ${{ secrets.GCP_IMAGE_REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/${{ github.event.repository.name }}
          APP_VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          docker push $APP_IMAGE:$APP_VERSION

      - name: Notify Discord (Build)
        if: always()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "Build by ${{ github.actor }}"
          description: "Container build and pushed to Artifact Registry"
          url: "https://github.com/Utotech-organize/rome-backoffice"
