export type LogEntry = {
  id: string;
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
  createdBy: string;
  createdById: string;
  updatedBy: string | null;
  updatedById: string | null;
  deletedBy: string | null;
  deletedById: string | null;
  createdByName: string;
  feature: string;
  event: string;
  messageTH: string;
  messageEN: string;
  organizationId: string;

  metadata: {
    ip: string;
    os: Record<string, unknown>;
    name: string;
    role: {
      id: string;
      name: string;
      status: string;
      createdAt: string;
      createdBy: string | null;
      deletedAt: string | null;
      deletedBy: string | null;
      updatedAt: string;
      updatedBy: string | null;
      createdById: string | null;
      deletedById: string | null;
      description: string | null;
      updatedById: string | null;
    };
    email: string;
    status: string;
    browser: string;
    location: string;
    createdAt: string;
  };

  reference: {
    ip: string;
    os: Record<string, unknown>;
    name: string;
    client: {
      name: string;
      type: string;
      version: string;
    };
    device: {
      id: string;
      type: string;
      brand: string;
      model: string;
    };
    status: string;
    dateTime: string;
    location: string;

    userData: {
      id: string;
      role: {
        id: string;
        name: string;
        status: string;
        createdAt: string;
        createdBy: string | null;
        deletedAt: string | null;
        deletedBy: string | null;
        updatedAt: string;
        updatedBy: string | null;
        createdById: string | null;
        deletedById: string | null;
        description: string | null;
        updatedById: string | null;
      };
      email: string;
      active: boolean;
      roleId: string;
      status: string;
      orderId: string | null;
      profile: {
        id: string;
        age: number | null;
        emId: string | null;
        phone: string | null;
        taxId: string | null;
        gender: string | null;
        height: number | null;
        prefix: string | null;
        skills: string | null;
        weight: number | null;
        imageUrl: string | null;
        isMobile: boolean;
        lastName: string | null;
        nickName: string | null;
        religion: string | null;
        birthDate: string | null;
        createdAt: string;
        createdBy: string | null;
        deletedAt: string | null;
        deletedBy: string | null;
        documents: unknown | null;
        firstName: string | null;
        updatedAt: string;
        updatedBy: string | null;
        lastNameTh: string | null;
        createdById: string | null;
        deletedById: string | null;
        deviceToken: string | null;
        endWorkDate: string | null;
        firstNameTh: string | null;
        nationality: string | null;
        socialMedia: unknown | null;
        updatedById: string | null;
        startWorkDate: string | null;
        workExperiences: unknown | null;
        compensationConfigs: unknown | null;
        educationInformations: unknown | null;
      };
      activate: boolean;
      branchId: string;
      password: string;
      userName: string;
      createdAt: string;
      createdBy: string | null;
      deletedAt: string | null;
      deletedBy: string | null;
      updatedAt: string;
      updatedBy: string | null;
      createdById: string | null;
      deletedById: string | null;
      updatedById: string | null;
      tempPassword: string | null;
      mainDepartment: string;
      organizationId: string;
    };

    userAgent: string;

    userAccount: {
      id: string;
      role: {
        id: string;
        name: string;
        status: string;
        createdAt: string;
        createdBy: string | null;
        deletedAt: string | null;
        deletedBy: string | null;
        updatedAt: string;
        updatedBy: string | null;
        createdById: string | null;
        deletedById: string | null;
        description: string | null;
        updatedById: string | null;
      };
      email: string;
      active: boolean;
      roleId: string;
      status: string;
      orderId: string | null;
      profile: {
        id: string;
        age: number | null;
        emId: string | null;
        phone: string | null;
        taxId: string | null;
        gender: string | null;
        height: number | null;
        prefix: string | null;
        skills: string | null;
        weight: number | null;
        imageUrl: string | null;
        isMobile: boolean;
        lastName: string | null;
        nickName: string | null;
        religion: string | null;
        birthDate: string | null;
        createdAt: string;
        createdBy: string | null;
        deletedAt: string | null;
        deletedBy: string | null;
        documents: unknown | null;
        firstName: string | null;
        updatedAt: string;
        updatedBy: string | null;
        lastNameTh: string | null;
        createdById: string | null;
        deletedById: string | null;
        deviceToken: string | null;
        endWorkDate: string | null;
        firstNameTh: string | null;
        nationality: string | null;
        socialMedia: unknown | null;
        updatedById: string | null;
        startWorkDate: string | null;
        workExperiences: unknown | null;
        compensationConfigs: unknown | null;
        educationInformations: unknown | null;
      };
      activate: boolean;
      branchId: string;
      password: string;
      userName: string;
      createdAt: string;
      createdBy: string | null;
      deletedAt: string | null;
      deletedBy: string | null;
      updatedAt: string;
      updatedBy: string | null;
      createdById: string | null;
      deletedById: string | null;
      updatedById: string | null;
      tempPassword: string | null;
      mainDepartment: string;
      organizationId: string;
    };

    userAgentData: string;
  };
};
